name: Build Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Capacitor
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run:
          npx cap copy android
          npx cap update android

