name: Build Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Capacitor
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        run:
          npx cap copy android
          npx cap update android

